name: RussellXY's blog site
description: Blogging about iOS
meta_description: "RussellXY's blog site, Blogging about iOS"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://russellxy_blog.com'
google_analytics: 'UA-XXXXXXXX-X'
encoding: UTF-8

# Details for the RSS feed generator
url:            'blog url'
author:         'RussellXY'
